name: Deploy database migrations and Edge functions to Production

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  deploy:
    name: Deploy database migrations and edge functions
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./supabase

    env:
      SUPABASE_ACCESS_TOKEN: ${{ secrets.SUPABASE_ACCESS_TOKEN }}
      SUPABASE_DB_PASSWORD: ${{ secrets.DB_PASSWORD }}
      SUPABASE_PROJECT_ID: ${{ vars.SUPABASE_PROJECT_ID }}
      # secrets for supabase edge functions
      TELEGRAM_BOT_TOKEN: ${{ secrets.TELEGRAM_BOT_TOKEN }}

    steps:
      - uses: actions/checkout@v4

      - uses: supabase/setup-cli@v1
        with:
          version: 2.58.5

      - run: supabase link --project-ref $SUPABASE_PROJECT_ID
      - run: supabase db push
      - name: Set secrets
        run: |
          supabase secrets set TELEGRAM_BOT_TOKEN=$TELEGRAM_BOT_TOKEN
      - run: supabase functions deploy --project-ref $SUPABASE_PROJECT_ID
